repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      types: [file]
      files: ^(gnatdbg/|setup).*\.py$
      args: [--line-length=79]
  - repo:  https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      types: [file]
      files: ^(gnatdbg/|setup).*\.py$
      additional_dependencies:
        - flake8-bugbear
        - flake8-builtins
        - flake8-comprehensions
        - flake8-docstrings
